const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=path.join(os.tmpdir(),'bittersweet-journey-check');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{
  const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);
  if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}
  fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}
    res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.jpg':'image/jpeg'})[path.extname(file)]||'application/octet-stream');res.end(data);});
});

(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:844,height:390}]){const page=await browser.newPage({viewport,reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api.mapbox.com/**',r=>r.abort());for(const section of [2]){await page.goto('http://127.0.0.1:'+server.address().port+'/site/chapters/mogao-caves/index.html?open=1&section='+section);await page.waitForFunction(()=>window.MOGAO_TERRAIN_RENDERER);await page.waitForTimeout(1000);await page.evaluate(section=>{window.MOGAO_TERRAIN_RENDERER.setState(section);document.body.classList.remove('mapbox-context-active');const context=document.querySelector('.mapbox-context');if(context)context.style.display='none';},section);await page.waitForTimeout(700);const result=await page.evaluate(()=>{const c=document.querySelector('.terrain-canvas'),gl=c.getContext('webgl');return {error:gl.getError(),w:c.width,h:c.height};});assert.equal(result.error,0);assert(result.w>0&&result.h>0);await page.screenshot({path:path.join(output,'mogao-expanded-'+viewport.width+'-'+section+'.png')});}assert.deepEqual(errors,[]);await page.close();}console.log('PASS: expanded DEMs render without WebGL errors at desktop, portrait and landscape sizes.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());